[package]
name = "chaos-core"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
serde = {workspace = true}
serde_yaml = {workspace = true}
serde_json = {workspace = true}